=== Bernardo-MG/Tabletop-Punkapocalyptic-Framework/src/main/resources/configuration/validation/punkapocalyptic-config-unit-weapon-initial.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="unit_weapon">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="equipment" type="equipment" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueUnit">
			<xs:selector xpath="equipment" />
			<xs:field xpath="unit" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="equipment">
		<xs:sequence>
			<xs:element name="unit" type="xs:token" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="constraints" type="constraints" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="weapon_selection" type="weaponList"
				maxOccurs="1" minOccurs="0">
				<xs:unique name="uniqueWeapon">
					<xs:selector xpath="weapon" />
					<xs:field xpath="name" />
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="constraints">
		<xs:sequence>
			<xs:element name="min_weapons" type="xs:int" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="max_weapons" type="xs:int" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="weaponList">
		<xs:sequence>
			<xs:element name="weapon" type="weapon" maxOccurs="unbounded"
	minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="weapon">
		<xs:sequence>
			<xs:element name="name" type="xs:token" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Punkapocalyptic-Framework/src/main/resources/configuration/punkapocalyptic-config-unit-weapon-initial.xml
<?xml version="1.0" encoding="UTF-8"?>
<unit_weapon xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/punkapocalyptic-config-unit-weapon-initial.xsd">
	<equipment>
		<unit>chief</unit>
		<constraints>
			<min_weapons>1</min_weapons>
			<max_weapons>2</max_weapons>
		</constraints>
		<weapon_selection>
			<weapon>
				<name>automatic_rifle</name>
			</weapon>
			<weapon>
				<name>crossbow</name>
			</weapon>
			<weapon>
				<name>mace</name>
			</weapon>
			<weapon>
				<name>medium_blade</name>
			</weapon>
			<weapon>
				<name>pistol</name>
			</weapon>
			<weapon>
				<name>rifle</name>
			</weapon>
			<weapon>
				<name>shotgun</name>
			</weapon>
		</weapon_selection>
	</equipment>
	<equipment>
		<unit>badass</unit>
		<constraints>
			<min_weapons>1</min_weapons>
			<max_weapons>2</max_weapons>
		</constraints>
		<weapon_selection>
			<weapon>
				<name>automatic_rifle</name>
			</weapon>
			<weapon>
				<name>crossbow</name>
			</weapon>
			<weapon>
				<name>mace</name>
			</weapon>
			<weapon>
				<name>medium_blade</name>
			</weapon>
			<weapon>
				<name>pistol</name>
			</weapon>
			<weapon>
				<name>rifle</name>
			</weapon>
			<weapon>
				<name>shotgun</name>
			</weapon>
		</weapon_selection>
	</equipment>
	<equipment>
		<unit>brute</unit>
		<constraints>
			<min_weapons>1</min_weapons>
			<max_weapons>2</max_weapons>
		</constraints>
		<weapon_selection>
			<weapon>
				<name>heavy_mace</name>
			</weapon>
			<weapon>
				<name>heavy_blade</name>
			</weapon>
			<weapon>
				<name>mace</name>
			</weapon>
			<weapon>
				<name>shield</name>
			</weapon>
			<weapon>
				<name>shotgun</name>
			</weapon>
		</weapon_selection>
	</equipment>
	<equipment>
		<unit>ganger</unit>
		<constraints>
			<min_weapons>1</min_weapons>
			<max_weapons>2</max_weapons>
		</constraints>
		<weapon_selection>
			<weapon>
				<name>crossbow</name>
			</weapon>
			<weapon>
				<name>bow</name>
			</weapon>
			<weapon>
				<name>light_mace</name>
			</weapon>
			<weapon>
				<name>mace</name>
			</weapon>
			<weapon>
				<name>medium_blade</name>
			</weapon>
			<weapon>
				<name>pistol</name>
			</weapon>
			<weapon>
				<name>rifle</name>
			</weapon>
			<weapon>
				<name>shotgun</name>
			</weapon>
			<weapon>
				<name>small_blade</name>
			</weapon>
			<weapon>
				<name>throwing_knives</name>
			</weapon>
		</weapon_selection>
	</equipment>
	<equipment>
		<unit>scumbag</unit>
		<constraints>
			<min_weapons>1</min_weapons>
			<max_weapons>2</max_weapons>
		</constraints>
		<weapon_selection>
			<weapon>
				<name>bow</name>
			</weapon>
			<weapon>
				<name>light_mace</name>
			</weapon>
			<weapon>
				<name>pistol</name>
			</weapon>
			<weapon>
				<name>small_blade</name>
			</weapon>
			<weapon>
				<name>throwing_knives</name>
			</weapon>
		</weapon_selection>
	</equipment>
</unit_weapon>
