=== Bernardo-MG/Tabletop-Punkapocalyptic-Framework/src/main/resources/model/validation/punkapocalyptic-model-unit-availability.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="availabilities">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="availability" type="availability" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="unit" />
			<xs:field xpath="." />
		</xs:unique>
	</xs:element>

	<xs:complexType name="availability">
		<xs:sequence>
			<xs:element name="unit" type="xs:token" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="armor" type="xs:token" maxOccurs="1"
				minOccurs="0" />
			<xs:element name="constraints" type="constraints"
				maxOccurs="1" minOccurs="1" />
			<xs:element name="weapons" type="weaponList" maxOccurs="1"
				minOccurs="0">
				<xs:unique name="uniqueWeapon">
					<xs:selector xpath="weapon" />
					<xs:field xpath="." />
				</xs:unique>
			</xs:element>
			<xs:element name="armors" type="armorList" maxOccurs="1"
				minOccurs="0">
				<xs:unique name="uniqueArmor">
					<xs:selector xpath="armor" />
					<xs:field xpath="name" />
				</xs:unique>
			</xs:element>
			<xs:element name="equipment_pieces" type="equipmentList"
				maxOccurs="1" minOccurs="0">
				<xs:unique name="uniqueEquipment">
					<xs:selector xpath="equipment_piece" />
					<xs:field xpath="." />
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="constraints">
		<xs:sequence>
			<xs:element name="min_weapons" type="xs:integer"
				maxOccurs="1" minOccurs="1" />
			<xs:element name="max_weapons" type="xs:integer"
				maxOccurs="1" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="weaponList">
		<xs:sequence>
			<xs:element name="weapon" type="xs:token" maxOccurs="unbounded"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="armorList">
		<xs:sequence>
			<xs:element name="armor" type="armorData" maxOccurs="unbounded"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="armorData">
		<xs:sequence>
			<xs:element name="name" type="xs:token" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="cost" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="equipmentList">
		<xs:sequence>
			<xs:element name="equipment_piece" type="xs:token"
				maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Punkapocalyptic-Framework/src/main/resources/model/punkapocalyptic-model-unit-availability.xml
<?xml version="1.0" encoding="UTF-8"?>
<availabilities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/punkapocalyptic-model-unit-availability.xsd">
	<availability>
		<unit>chief</unit>
		<armor>hardened_leather</armor>
		<constraints>
			<min_weapons>1</min_weapons>
			<max_weapons>2</max_weapons>
		</constraints>
		<weapons>
			<weapon>automatic_rifle</weapon>
			<weapon>crossbow</weapon>
			<weapon>mace</weapon>
			<weapon>medium_blade</weapon>
			<weapon>pistol</weapon>
			<weapon>rifle</weapon>
			<weapon>shotgun</weapon>
		</weapons>
		<armors>
			<armor>
				<name>bulletproof_vest</name>
				<cost>10</cost>
			</armor>
			<armor>
				<name>metallic_armor</name>
				<cost>10</cost>
			</armor>
		</armors>
	</availability>
	<availability>
		<unit>badass</unit>
		<armor>thick_clothes</armor>
		<constraints>
			<min_weapons>1</min_weapons>
			<max_weapons>2</max_weapons>
		</constraints>
		<weapons>
			<weapon>automatic_rifle</weapon>
			<weapon>crossbow</weapon>
			<weapon>mace</weapon>
			<weapon>medium_blade</weapon>
			<weapon>pistol</weapon>
			<weapon>rifle</weapon>
			<weapon>shotgun</weapon>
		</weapons>
		<armors>
			<armor>
				<name>hardened_leather</name>
				<cost>5</cost>
			</armor>
			<armor>
				<name>metallic_armor</name>
				<cost>15</cost>
			</armor>
		</armors>
	</availability>
	<availability>
		<unit>brute</unit>
		<armor>hardened_leather</armor>
		<constraints>
			<min_weapons>1</min_weapons>
			<max_weapons>2</max_weapons>
		</constraints>
		<weapons>
			<weapon>heavy_blade</weapon>
			<weapon>heavy_mace</weapon>
			<weapon>mace</weapon>
			<weapon>shotgun</weapon>
		</weapons>
		<armors>
			<armor>
				<name>metallic_armor</name>
				<cost>10</cost>
			</armor>
			<armor>
				<name>metal_plate</name>
				<cost>15</cost>
			</armor>
		</armors>
		<equipment_pieces>
			<equipment_piece>shield</equipment_piece>
		</equipment_pieces>
	</availability>
	<availability>
		<unit>ganger</unit>
		<armor>thick_clothes</armor>
		<constraints>
			<min_weapons>1</min_weapons>
			<max_weapons>2</max_weapons>
		</constraints>
		<weapons>
			<weapon>bow</weapon>
			<weapon>crossbow</weapon>
			<weapon>light_mace</weapon>
			<weapon>medium_blade</weapon>
			<weapon>mace</weapon>
			<weapon>pistol</weapon>
			<weapon>rifle</weapon>
			<weapon>shotgun</weapon>
			<weapon>small_blade</weapon>
			<weapon>throwing_knife</weapon>
		</weapons>
		<armors>
			<armor>
				<name>hardened_leather</name>
				<cost>5</cost>
			</armor>
		</armors>
	</availability>
	<availability>
		<unit>scumbag</unit>
		<armor>thick_clothes</armor>
		<constraints>
			<min_weapons>1</min_weapons>
			<max_weapons>2</max_weapons>
		</constraints>
		<weapons>
			<weapon>bow</weapon>
			<weapon>light_mace</weapon>
			<weapon>pistol</weapon>
			<weapon>small_blade</weapon>
			<weapon>throwing_knife</weapon>
		</weapons>
	</availability>
</availabilities>
