=== Bernardo-MG/Tabletop-Punkapocalyptic-Framework/src/main/resources/model/validation/punkapocalyptic-model-armor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:punka="http://www.wandrell.com/tabletop/validation/punkapocalyptic/model">
	<xs:import schemaLocation="punkapocalyptic-model.xsd"
		namespace="http://www.wandrell.com/tabletop/validation/punkapocalyptic/model" />

	<xs:element name="armors">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="armor" type="armor" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="armor" />
			<xs:field xpath="name" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="armor">
		<xs:sequence>
			<xs:element name="name" type="xs:token" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="constraints" type="punka:constraints"
				maxOccurs="1" minOccurs="0">
				<xs:unique name="uniqueConstraint">
					<xs:selector xpath="constraint" />
					<xs:field xpath="." />
				</xs:unique>
			</xs:element>
			<xs:element name="rules" type="punka:rules" maxOccurs="1"
				minOccurs="0">
				<xs:unique name="uniqueRule">
					<xs:selector xpath="rule" />
					<xs:field xpath="." />
				</xs:unique>
			</xs:element>
			<xs:element name="protection" type="xs:int" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="protection_ranged" type="punka:ranges"
				maxOccurs="1" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Punkapocalyptic-Framework/src/main/resources/model/punkapocalyptic-model-armor.xml
<?xml version="1.0" encoding="UTF-8"?>
<armors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/punkapocalyptic-model-armor.xsd">
	<armor>
		<name>bulletproof_vest</name>
		<modifiers>
			<modifier>firearms_protection</modifier>
		</modifiers>
		<protection>3</protection>
	</armor>
	<armor>
		<name>hardened_leather</name>
		<protection>2</protection>
	</armor>
	<armor>
		<name>metal_plate</name>
		<rules>
			<rule>cumbersome</rule>
		</rules>
		<protection>5</protection>
	</armor>
	<armor>
		<name>metallic_armor</name>
		<protection>4</protection>
	</armor>
	<armor>
		<name>thick_clothes</name>
		<protection>1</protection>
	</armor>
</armors>
