=== Bernardo-MG/Tabletop-Punkapocalyptic-Framework/src/main/resources/model/validation/punkapocalyptic-model-weapon-enhancement.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="weapon_enhacement_profiles">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="weapon_enhacement_profile" type="enhacement" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="enhacement" />
			<xs:field xpath="name" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="enhacement">
		<xs:sequence>
			<xs:element name="name" type="xs:token" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="constraints" type="constraints"
				maxOccurs="1" minOccurs="0">
				<xs:unique name="uniqueConstraint">
					<xs:selector xpath="constraint" />
					<xs:field xpath="." />
				</xs:unique>
			</xs:element>
			<xs:element name="bonus_list" type="bonusList"
				maxOccurs="1" minOccurs="0">
				<xs:unique name="uniqueBonus">
					<xs:selector xpath="bonus" />
					<xs:field xpath="attribute" />
				</xs:unique>
			</xs:element>
			<xs:element name="cost" type="xs:int" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- This should be imported -->

	<xs:simpleType name="attribute">
		<xs:restriction base="xs:token">
			<xs:enumeration value="actions" />
			<xs:enumeration value="combat" />
			<xs:enumeration value="precision" />
			<xs:enumeration value="agility" />
			<xs:enumeration value="strength" />
			<xs:enumeration value="toughness" />
			<xs:enumeration value="tech" />
			<xs:enumeration value="penetration" />
			<xs:enumeration value="armor" />
			<xs:enumeration value="cover" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="constraints">
		<xs:sequence>
			<xs:element name="constraint" type="xs:token" maxOccurs="unbounded"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="rules">
		<xs:sequence>
			<xs:element name="rule" type="xs:token" maxOccurs="unbounded"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="bonusList">
		<xs:sequence>
			<xs:element name="bonus" type="bonus" maxOccurs="unbounded"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="bonus">
		<xs:sequence>
			<xs:element name="attribute" type="attribute"
				maxOccurs="1" minOccurs="1" />
			<xs:element name="value" type="xs:int" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ranges">
		<xs:sequence>
			<xs:element name="short" type="xs:int" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="medium" type="xs:int" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="long" type="xs:int" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Punkapocalyptic-Framework/src/main/resources/model/punkapocalyptic-model-weapon-enhancement.xml
<?xml version="1.0" encoding="UTF-8"?>
<weapon_enhacement_profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/punkapocalyptic-model-weapon-enhancement.xsd">
	<weapon_enhacement_profile>
		<name>bayonet</name>
		<bonus_list>
			<bonus>
				<attribute>penetration</attribute>
				<value>2</value>
			</bonus>
		</bonus_list>
		<cost>4</cost>
	</weapon_enhacement_profile>
</weapon_enhacement_profiles>
