=== Bernardo-MG/Tabletop-Punkapocalyptic-Framework/src/test/resources/parameter/constraint_up_to_count.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="test_data">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="data" type="checkList" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="checkList">
		<xs:sequence>
			<xs:element name="unit" type="xs:string" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="count" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="list" type="unitList" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
		<xs:attribute name="valid" type="xs:boolean" use="required" />
	</xs:complexType>

	<xs:complexType name="unitList">
		<xs:sequence>
			<xs:element name="unit" type="xs:string" maxOccurs="unbounded"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Punkapocalyptic-Framework/src/test/resources/parameter/constraint_up_to_count.xml
<?xml version="1.0" encoding="UTF-8"?>
<test_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="constraint_up_to_count.xsd">
	<!-- Count: 0 -->
	<data valid="true">
		<count>0</count>
		<valid>0</valid>
	</data>
	<data valid="false">
		<count>0</count>
		<valid>1</valid>
	</data>
	<data valid="false">
		<count>0</count>
		<valid>3</valid>
	</data>
	<data valid="false">
		<count>0</count>
		<valid>3</valid>
	</data>
	<!-- Count: 1 -->
	<data valid="true">
		<count>1</count>
		<valid>0</valid>
	</data>
	<data valid="true">
		<count>1</count>
		<valid>1</valid>
	</data>
	<data valid="false">
		<count>1</count>
		<valid>2</valid>
	</data>
	<data valid="false">
		<count>1</count>
		<valid>3</valid>
	</data>
	<!-- Count: 5 -->
	<data valid="true">
		<count>5</count>
		<valid>0</valid>
	</data>
	<data valid="true">
		<count>5</count>
		<valid>1</valid>
	</data>
	<data valid="true">
		<count>5</count>
		<valid>2</valid>
	</data>
	<data valid="true">
		<count>5</count>
		<valid>3</valid>
	</data>
	<data valid="true">
		<count>5</count>
		<valid>4</valid>
	</data>
	<data valid="true">
		<count>5</count>
		<valid>5</valid>
	</data>
	<data valid="false">
		<count>5</count>
		<valid>6</valid>
	</data>
	<data valid="false">
		<count>5</count>
		<valid>10</valid>
	</data>
	<!-- Count: 10 -->
	<data valid="true">
		<count>10</count>
		<valid>0</valid>
	</data>
	<data valid="true">
		<count>10</count>
		<valid>1</valid>
	</data>
	<data valid="true">
		<count>10</count>
		<valid>2</valid>
	</data>
	<data valid="true">
		<count>10</count>
		<valid>10</valid>
	</data>
	<data valid="false">
		<count>10</count>
		<valid>11</valid>
	</data>
	<data valid="false">
		<count>10</count>
		<valid>100</valid>
	</data>
	<!-- Count: MAX -->
	<data valid="true">
		<count>2147483647</count>
		<valid>0</valid>
	</data>
	<data valid="true">
		<count>2147483647</count>
		<valid>1</valid>
	</data>
	<data valid="true">
		<count>2147483647</count>
		<valid>10</valid>
	</data>
	<data valid="true">
		<count>2147483647</count>
		<valid>100</valid>
	</data>
</test_data>
