=== Bernardo-MG/Tabletop-Punkapocalyptic-Framework/src/test/resources/parameter/constraint_unit_limit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="test_data">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="data" type="checkList" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="data" />
			<xs:field xpath="units" />
			<xs:field xpath="limit" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="checkList">
		<xs:sequence>
			<xs:element name="units" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="limit" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
		<xs:attribute name="valid" type="xs:boolean" use="required" />
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Punkapocalyptic-Framework/src/test/resources/parameter/constraint_unit_limit.xml
<?xml version="1.0" encoding="UTF-8"?>
<test_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="constraint_unit_limit.xsd">
	<!-- Limit 0 -->
	<data valid="true">
		<units>0</units>
		<limit>0</limit>
	</data>
	<data valid="false">
		<units>1</units>
		<limit>0</limit>
	</data>
	<data valid="false">
		<units>10</units>
		<limit>0</limit>
	</data>
	<data valid="false">
		<units>2147483647</units>
		<limit>0</limit>
	</data>
	<!-- Limit 1 -->
	<data valid="true">
		<units>0</units>
		<limit>1</limit>
	</data>
	<data valid="true">
		<units>1</units>
		<limit>1</limit>
	</data>
	<data valid="false">
		<units>10</units>
		<limit>1</limit>
	</data>
	<data valid="false">
		<units>2147483647</units>
		<limit>1</limit>
	</data>
	<!-- Limit 100 -->
	<data valid="true">
		<units>0</units>
		<limit>100</limit>
	</data>
	<data valid="true">
		<units>1</units>
		<limit>100</limit>
	</data>
	<data valid="true">
		<units>10</units>
		<limit>100</limit>
	</data>
	<data valid="true">
		<units>99</units>
		<limit>100</limit>
	</data>
	<data valid="true">
		<units>100</units>
		<limit>100</limit>
	</data>
	<data valid="false">
		<units>101</units>
		<limit>100</limit>
	</data>
	<data valid="false">
		<units>2147483647</units>
		<limit>100</limit>
	</data>
	<!-- Limit MAX -->
	<data valid="true">
		<units>0</units>
		<limit>2147483647</limit>
	</data>
	<data valid="true">
		<units>1</units>
		<limit>2147483647</limit>
	</data>
	<data valid="true">
		<units>10</units>
		<limit>2147483647</limit>
	</data>
	<data valid="true">
		<units>2147483647</units>
		<limit>2147483647</limit>
	</data>
</test_data>
