=== Bernardo-MG/Tabletop-Punkapocalyptic-Framework/src/test/resources/parameter/constraint_dependant.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="test_data">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="data" type="checkList" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="data" />
			<xs:field xpath="dependant" />
			<xs:field xpath="master" />
			<xs:field xpath="range" />
			<xs:field xpath="gangSize" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="checkList">
		<xs:sequence>
			<xs:element name="dependant" maxOccurs="1" minOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="master" maxOccurs="1" minOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="range" maxOccurs="1" minOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="valid" type="xs:boolean" use="required" />
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Punkapocalyptic-Framework/src/test/resources/parameter/constraint_dependant.xml
<?xml version="1.0" encoding="UTF-8"?>
<test_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="constraint_dependant.xsd">
	<!-- Gang size 0 -->
	<data valid="true">
		<dependant>0</dependant>
		<master>0</master>
		<range>100</range>
	</data>
	<data valid="true">
		<dependant>0</dependant>
		<master>0</master>
		<range>0</range>
	</data>
	<!-- Gang size 1 -->
	<data valid="true">
		<dependant>0</dependant>
		<master>0</master>
		<range>2</range>
	</data>
	<data valid="true">
		<dependant>0</dependant>
		<master>1</master>
		<range>2</range>
	</data>
	<data valid="false">
		<dependant>1</dependant>
		<master>0</master>
		<range>2</range>
	</data>
	<!-- Gang size 10 -->
	<data valid="true">
		<dependant>0</dependant>
		<master>0</master>
		<range>2</range>
	</data>
	<data valid="true">
		<dependant>0</dependant>
		<master>1</master>
		<range>2</range>
	</data>
	<data valid="true">
		<dependant>1</dependant>
		<master>1</master>
		<range>2</range>
	</data>
	<data valid="true">
		<dependant>2</dependant>
		<master>1</master>
		<range>2</range>
	</data>
	<data valid="false">
		<dependant>3</dependant>
		<master>1</master>
		<range>2</range>
	</data>
	<data valid="false">
		<dependant>5</dependant>
		<master>1</master>
		<range>2</range>
	</data>
	<data valid="true">
		<dependant>0</dependant>
		<master>2</master>
		<range>2</range>
	</data>
	<data valid="true">
		<dependant>4</dependant>
		<master>2</master>
		<range>2</range>
	</data>
	<data valid="false">
		<dependant>5</dependant>
		<master>2</master>
		<range>2</range>
	</data>
	<data valid="true">
		<dependant>0</dependant>
		<master>3</master>
		<range>2</range>
	</data>
	<data valid="true">
		<dependant>1</dependant>
		<master>3</master>
		<range>2</range>
	</data>
	<data valid="true">
		<dependant>6</dependant>
		<master>3</master>
		<range>2</range>
	</data>
	<data valid="false">
		<dependant>7</dependant>
		<master>3</master>
		<range>2</range>
	</data>
</test_data>
