=== Bernardo-MG/Tabletop-Punkapocalyptic-Framework/src/test/resources/parameter/max-allowed-units.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="test_data">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="data" type="data" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="data" />
			<xs:field xpath="points" />
			<xs:field xpath="units" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="data">
		<xs:sequence>
			<xs:element name="points" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="units" default="1"
				maxOccurs="1" >
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== Bernardo-MG/Tabletop-Punkapocalyptic-Framework/src/test/resources/parameter/max-allowed-units.xml
<?xml version="1.0" encoding="UTF-8"?>
<test_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="max-allowed-units.xsd">
	<data>
		<points>-2147483648</points>
		<units>0</units>
	</data>
	<data>
		<points>-100</points>
		<units>0</units>
	</data>
	<data>
		<points>-10</points>
		<units>0</units>
	</data>
	<data>
		<points>-3</points>
		<units>0</units>
	</data>
	<data>
		<points>-2</points>
		<units>0</units>
	</data>
	<data>
		<points>-1</points>
		<units>0</units>
	</data>
	<data>
		<points>0</points>
		<units>3</units>
	</data>
	<data>
		<points>1</points>
		<units>3</units>
	</data>
	<data>
		<points>2</points>
		<units>3</units>
	</data>
	<data>
		<points>48</points>
		<units>3</units>
	</data>
	<data>
		<points>49</points>
		<units>3</units>
	</data>
	<data>
		<points>50</points>
		<units>3</units>
	</data>
	<data>
		<points>51</points>
		<units>3</units>
	</data>
	<data>
		<points>52</points>
		<units>3</units>
	</data>
	<data>
		<points>98</points>
		<units>3</units>
	</data>
	<data>
		<points>99</points>
		<units>3</units>
	</data>
	<data>
		<points>100</points>
		<units>3</units>
	</data>
	<data>
		<points>101</points>
		<units>6</units>
	</data>
	<data>
		<points>102</points>
		<units>6</units>
	</data>
	<data>
		<points>103</points>
		<units>6</units>
	</data>
	<data>
		<points>148</points>
		<units>6</units>
	</data>
	<data>
		<points>149</points>
		<units>6</units>
	</data>
	<data>
		<points>150</points>
		<units>6</units>
	</data>
	<data>
		<points>151</points>
		<units>6</units>
	</data>
	<data>
		<points>152</points>
		<units>6</units>
	</data>
	<data>
		<points>198</points>
		<units>6</units>
	</data>
	<data>
		<points>199</points>
		<units>6</units>
	</data>
	<data>
		<points>200</points>
		<units>6</units>
	</data>
	<data>
		<points>201</points>
		<units>9</units>
	</data>
	<data>
		<points>202</points>
		<units>9</units>
	</data>
	<data>
		<points>203</points>
		<units>9</units>
	</data>
	<data>
		<points>248</points>
		<units>9</units>
	</data>
	<data>
		<points>249</points>
		<units>9</units>
	</data>
	<data>
		<points>250</points>
		<units>9</units>
	</data>
	<data>
		<points>251</points>
		<units>9</units>
	</data>
	<data>
		<points>252</points>
		<units>9</units>
	</data>
	<data>
		<points>298</points>
		<units>9</units>
	</data>
	<data>
		<points>299</points>
		<units>9</units>
	</data>
	<data>
		<points>300</points>
		<units>9</units>
	</data>
	<data>
		<points>301</points>
		<units>12</units>
	</data>
	<data>
		<points>302</points>
		<units>12</units>
	</data>
	<data>
		<points>303</points>
		<units>12</units>
	</data>
	<data>
		<points>348</points>
		<units>12</units>
	</data>
	<data>
		<points>349</points>
		<units>12</units>
	</data>
	<data>
		<points>350</points>
		<units>12</units>
	</data>
	<data>
		<points>351</points>
		<units>12</units>
	</data>
	<data>
		<points>352</points>
		<units>12</units>
	</data>
	<data>
		<points>398</points>
		<units>12</units>
	</data>
	<data>
		<points>399</points>
		<units>12</units>
	</data>
	<data>
		<points>400</points>
		<units>12</units>
	</data>
	<data>
		<points>401</points>
		<units>15</units>
	</data>
	<data>
		<points>402</points>
		<units>15</units>
	</data>
	<data>
		<points>403</points>
		<units>15</units>
	</data>
	<data>
		<points>448</points>
		<units>15</units>
	</data>
	<data>
		<points>449</points>
		<units>15</units>
	</data>
	<data>
		<points>450</points>
		<units>15</units>
	</data>
	<data>
		<points>451</points>
		<units>15</units>
	</data>
	<data>
		<points>452</points>
		<units>15</units>
	</data>
	<data>
		<points>498</points>
		<units>15</units>
	</data>
	<data>
		<points>499</points>
		<units>15</units>
	</data>
	<data>
		<points>500</points>
		<units>15</units>
	</data>
	<data>
		<points>501</points>
		<units>18</units>
	</data>
	<data>
		<points>502</points>
		<units>18</units>
	</data>
	<data>
		<points>503</points>
		<units>18</units>
	</data>
	<data>
		<points>548</points>
		<units>18</units>
	</data>
	<data>
		<points>549</points>
		<units>18</units>
	</data>
	<data>
		<points>550</points>
		<units>18</units>
	</data>
	<data>
		<points>551</points>
		<units>18</units>
	</data>
	<data>
		<points>552</points>
		<units>18</units>
	</data>
	<data>
		<points>598</points>
		<units>18</units>
	</data>
	<data>
		<points>599</points>
		<units>18</units>
	</data>
	<data>
		<points>600</points>
		<units>18</units>
	</data>
</test_data>
